### PR TITLE
Added the activeLinkable property to LinkPager class

### PR DESCRIPTION
**Pull request by IgorSalevan**
This revision helps to follow SEO recommendation of Google. It sounds that an HTML page must avoid internal links to itself.

### CODE REVIEW

**Comment by justinvoelker** [comment]
If this is for the sake of SEO I actually like the idea of making it false by default (since false by default isn't really taking away any functionality but is improving SEO).

Rather than merge here I'd like to see this added to the LinkPager class directly in Yii. Submit a pull request there and if Yii doesn't merge your suggested change I'll definitely add it here.  Sound good?

**Comment by IgorSalevan** [comment]
Thanx for this idea. I'll make a pull request to Yii and keep in touch with you.

**Comment by IgorSalevan** [comment]
I tried but alas: https://github.com/yiisoft/yii2/pull/8437

**Comment by justinvoelker** [comment]
It was worth a shot.  Since this appears to not be a hard set SEO rule, we'll leave the default the way it is.  I'm thinking about a couple updates but may merge as is.  Thanks for the contribution!

**Comment by IgorSalevan** [comment]
Ok. Thank you, man.

**Comment by justinvoelker** [comment]
Sorry this took so long to merge.  I was hoping to find a way to tweak _renderPageButtons_ that didn't require _renderPageButton_ being added.  It would have worked with a reordering of the delivered css/less but I don't want that.

Also, I change the property name to _activePageAsLink_ to follow the existing properties a little closer and be a little more descriptive.

**Comment by IgorSalevan** [comment]
The name `activePageAsLink` sounds much better. That's great, thank you.
Tried to add you in skype but it seems you don't use it.

**Pull request merged**
